[package]
name = "trigger_sdl2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.36.0"
trigger_display = { version = "0.1.0", path = "../trigger_display" }
